/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface WebViewInit {
    width: number;
    height: number;
    resizable: boolean;
    debug: boolean;
    title: string;
    content: string;
    renderAsHtml: boolean;
}
export class Window {
    constructor(options: WebViewInit);
    setTitle(title: string): void;
    evaluate(js: string): void;
    injectCSS(css: string): void;
    exit(): void;
    run(sync: boolean): void;
}
